name: beta

on:
  push:
    #branches:
    #  - master
    tags:
      - 'v*-b*'
    #tags-ignore:
    #  - 'v*-*'

env:
  APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
  APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
  APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
  FASTLANE_USERNAME: ${{ secrets.FASTLANE_USERNAME }}
  FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
  MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
  MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
  MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
  MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
  DELIVER_USERNAME: ${{ secrets.DELIVER_USERNAME }}
  PILOT_USERNAME: ${{ secrets.PILOT_USERNAME }}
  PILOT_GROUPS: ${{ secrets.PILOT_GROUPS }}
  PILOT_BETA_APP_FEEDBACK: ${{ secrets.PILOT_BETA_APP_FEEDBACK }}
  PILOT_BETA_APP_REVIEW_INFO: ${{ secrets.PILOT_BETA_APP_REVIEW_INFO }}
  APPCENTER_OWNER_NAME: ${{ secrets.APPCENTER_OWNER_NAME }}
  APPCENTER_API_TOKEN: ${{ secrets.APPCENTER_API_TOKEN }}

jobs:
  upload_to_testflight:
    runs-on: macos-10.15
    timeout-minutes: 60
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # for proper build number
          submodules: true
      - name: Prepare Ruby bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Cache CocoaPods
        uses: actions/cache@v2
        with:
          path: |
            Pods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Prepare for fastlane match
        run: |
          scripts/ci/recognize-match-hostname.sh
          bundle exec fastlane preinstall_development_certs
      - name: Build (macOS)
        run: |
          bundle exec fastlane --env mac,beta create_archive
          scripts/ci/reset-archive.sh
      - name: Build (iOS)
        run: |
          bundle exec fastlane --env ios,beta create_archive
          scripts/ci/reset-archive.sh
      - name: Submit to TestFlight (macOS)
        run: |
          PILOT_CHANGELOG=`ci/build-changelog.sh mac` bundle exec fastlane --env mac,beta beta_deploy
      - name: Submit to TestFlight (iOS)
        run: |
          PILOT_CHANGELOG=`ci/build-changelog.sh ios` bundle exec fastlane --env ios,beta beta_deploy
