name: Public Beta

on:
  push:
    branches:
      - 'master'
      - 'stable'
    #tags:
    #  - 'v*-b*'
    #tags-ignore:
    #  - 'v*-*'

env:
  APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
  FASTLANE_USERNAME: ${{ secrets.FASTLANE_USERNAME }}
  FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
  MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
  MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
  MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
  MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
  PILOT_USERNAME: ${{ secrets.PILOT_USERNAME }}
  PILOT_GROUPS: ${{ secrets.PILOT_GROUPS }}
  PILOT_BETA_APP_FEEDBACK: ${{ secrets.PILOT_BETA_APP_FEEDBACK }}
  PILOT_BETA_APP_REVIEW_INFO: ${{ secrets.PILOT_BETA_APP_REVIEW_INFO }}
  CHANGELOG_PREFACE: ${{ secrets.CHANGELOG_PREFACE }}

jobs:
  run_tests:
    if: github.ref != 'refs/heads/stable'
    runs-on: macos-11
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Prepare build
        uses: ./.github/actions/prepare-build-app
      - name: Run tests
        run: |
          bundle exec fastlane --env mac,beta test_target
  build_upload_ios:
    if: github.ref == 'refs/heads/stable'
    runs-on: macos-11
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Prepare build
        uses: ./.github/actions/prepare-build-app
      - name: Build iOS (.ipa)
        run: |
          bundle exec fastlane --env ios,beta create_archive
      - name: Submit to TestFlight
        run: |
          export PILOT_CHANGELOG=`ci/build-changelog.sh ios`
          export PILOT_IPA="dist/ios/Passepartout.ipa"
          bundle exec fastlane --env ios,beta store_beta
  build_upload_mac:
    if: github.ref == 'refs/heads/stable'
    runs-on: macos-11
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Prepare build
        uses: ./.github/actions/prepare-build-app
      - name: Build macOS (.pkg)
        run: |
          bundle exec fastlane --env mac,beta create_archive
      - name: Submit to TestFlight
        run: |
          export PILOT_CHANGELOG=`ci/build-changelog.sh mac`
          export PILOT_PKG="dist/mac/Passepartout.pkg"
          bundle exec fastlane --env mac,beta store_beta
  release_public_beta:
    if: github.ref == 'refs/heads/stable'
    runs-on: ubuntu-latest
    needs: [build_upload_ios, build_upload_mac]
    environment:
      name: public_beta
    env:
      PILOT_USERNAME: ${{ secrets.PILOT_USERNAME }}
      PILOT_GROUPS: ${{ secrets.PILOT_GROUPS }}
      PILOT_DISTRIBUTE_ONLY: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Prepare Ruby bundle
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Publish on TestFlight (iOS)
        run: |
          export PILOT_APP_VERSION=`ci/version-number.sh ios`
          export PILOT_BUILD_NUMBER=`ci/build-number.sh ios`
          bundle exec fastlane --env ios,beta store_beta
#      - name: Publish on TestFlight (macOS)
#        run: |
#          export PILOT_APP_VERSION=`ci/version-number.sh mac`
#          export PILOT_BUILD_NUMBER=`ci/build-number.sh mac`
#          bundle exec fastlane --env mac,beta store_beta
  submit_for_app_review:
    if: github.ref == 'refs/heads/stable'
    runs-on: ubuntu-latest
    needs: release_public_beta
    environment:
      name: app_review
    env:
      DELIVER_USERNAME: ${{ secrets.DELIVER_USERNAME }}
      DELIVER_FORCE: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Prepare Ruby bundle
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Submit for App Review (iOS)
        run: |
          export DELIVER_APP_VERSION=`ci/version-number.sh ios`
          export DELIVER_BUILD_NUMBER=`ci/build-number.sh ios`
          bundle exec fastlane --env ios store_review add_id_info_uses_idfa:false
      - name: Submit for App Review (macOS)
        run: |
          export DELIVER_APP_VERSION=`ci/version-number.sh mac`
          export DELIVER_BUILD_NUMBER=`ci/build-number.sh mac`
          bundle exec fastlane --env mac store_review add_id_info_uses_idfa:false
